//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterWebMiningApp.Localization.Resume {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LResumePage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LResumePage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MasterWebMiningApp.Localization.Resume.LResumePage", typeof(LResumePage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.3.
        /// </summary>
        public static string AverageGrade {
            get {
                return ResourceManager.GetString("AverageGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Курсы по Vue.js + Oracle.
        /// </summary>
        public static string Courses {
            get {
                return ResourceManager.GetString("Courses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PostgreSQL 13.
        /// </summary>
        public static string DBMS1 {
            get {
                return ResourceManager.GetString("DBMS1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSSQL.
        /// </summary>
        public static string DBMS2 {
            get {
                return ResourceManager.GetString("DBMS2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 04.08.2001.
        /// </summary>
        public static string Dob {
            get {
                return ResourceManager.GetString("Dob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ава групп, системный администратор, 3 недели.
        /// </summary>
        public static string Exp {
            get {
                return ResourceManager.GetString("Exp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASP.NET Core.
        /// </summary>
        public static string Frameworks1 {
            get {
                return ResourceManager.GetString("Frameworks1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASP.NET WebApi.
        /// </summary>
        public static string Frameworks2 {
            get {
                return ResourceManager.GetString("Frameworks2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blazor WebAssembly.
        /// </summary>
        public static string Frameworks3 {
            get {
                return ResourceManager.GetString("Frameworks3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity Framework Core 6.
        /// </summary>
        public static string Frameworks4 {
            get {
                return ResourceManager.GetString("Frameworks4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Средний балл.
        /// </summary>
        public static string HAverageGrade {
            get {
                return ResourceManager.GetString("HAverageGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дополнительные курсы.
        /// </summary>
        public static string HCourses {
            get {
                return ResourceManager.GetString("HCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to СУБД.
        /// </summary>
        public static string HDBMS {
            get {
                return ResourceManager.GetString("HDBMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата рождения.
        /// </summary>
        public static string HDob {
            get {
                return ResourceManager.GetString("HDob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2019-2023 гг.: бакалавриат КубГУ.
        /// </summary>
        public static string Hei {
            get {
                return ResourceManager.GetString("Hei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Опыт работы.
        /// </summary>
        public static string HExp {
            get {
                return ResourceManager.GetString("HExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ФИО.
        /// </summary>
        public static string HFio {
            get {
                return ResourceManager.GetString("HFio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фреймворки.
        /// </summary>
        public static string HFrameworks {
            get {
                return ResourceManager.GetString("HFrameworks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профессиональная специализация и владение компьютером.
        /// </summary>
        public static string HHardSkills {
            get {
                return ResourceManager.GetString("HHardSkills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ВУЗ.
        /// </summary>
        public static string HHei {
            get {
                return ResourceManager.GetString("HHei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Увлечения.
        /// </summary>
        public static string HHobbies {
            get {
                return ResourceManager.GetString("HHobbies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Владение языками.
        /// </summary>
        public static string HLang {
            get {
                return ResourceManager.GetString("HLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Методики.
        /// </summary>
        public static string HMetodics {
            get {
                return ResourceManager.GetString("HMetodics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Компьютерные игры.
        /// </summary>
        public static string Hobbies1 {
            get {
                return ResourceManager.GetString("Hobbies1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Книги (русская классика, научная фантастика, классическая литература).
        /// </summary>
        public static string Hobbies2 {
            get {
                return ResourceManager.GetString("Hobbies2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Музыка (EDM, Lo-fi).
        /// </summary>
        public static string Hobbies3 {
            get {
                return ResourceManager.GetString("Hobbies3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кинематограф (Детектив).
        /// </summary>
        public static string Hobbies4 {
            get {
                return ResourceManager.GetString("Hobbies4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Планы на будущее.
        /// </summary>
        public static string HPlans {
            get {
                return ResourceManager.GetString("HPlans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Платформы.
        /// </summary>
        public static string HPlatforms {
            get {
                return ResourceManager.GetString("HPlatforms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Место рождения.
        /// </summary>
        public static string HPob {
            get {
                return ResourceManager.GetString("HPob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Языки программирования.
        /// </summary>
        public static string HProgLangs {
            get {
                return ResourceManager.GetString("HProgLangs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Парадигмы программирования.
        /// </summary>
        public static string HProgrammingParadigms {
            get {
                return ResourceManager.GetString("HProgrammingParadigms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Школа.
        /// </summary>
        public static string HSchool {
            get {
                return ResourceManager.GetString("HSchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Личные качества.
        /// </summary>
        public static string HSoftSkills {
            get {
                return ResourceManager.GetString("HSoftSkills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Системы контроля версий.
        /// </summary>
        public static string HVCS {
            get {
                return ResourceManager.GetString("HVCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Русский – родной.
        /// </summary>
        public static string Lang1 {
            get {
                return ResourceManager.GetString("Lang1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Английский – средний уровень.
        /// </summary>
        public static string Lang2 {
            get {
                return ResourceManager.GetString("Lang2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOLID.
        /// </summary>
        public static string Metodics1 {
            get {
                return ResourceManager.GetString("Metodics1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REST.
        /// </summary>
        public static string Metodics2 {
            get {
                return ResourceManager.GetString("Metodics2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дальнейшее профессиональное и карьерное развитие в качестве разработчика ПО, в том числе изучение новых методик и паттернов программирования, фреймворков, технологий и языков программирования, исследовать настолько много мест в России, насколько это возможно.
        /// </summary>
        public static string Plans {
            get {
                return ResourceManager.GetString("Plans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .Net Framework 4.7.2.
        /// </summary>
        public static string Platforms1 {
            get {
                return ResourceManager.GetString("Platforms1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET 5.
        /// </summary>
        public static string Platforms2 {
            get {
                return ResourceManager.GetString("Platforms2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to г. Краснодар.
        /// </summary>
        public static string Pob {
            get {
                return ResourceManager.GetString("Pob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C#.
        /// </summary>
        public static string ProgLangs1 {
            get {
                return ResourceManager.GetString("ProgLangs1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typescript.
        /// </summary>
        public static string ProgLangs2 {
            get {
                return ResourceManager.GetString("ProgLangs2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL.
        /// </summary>
        public static string ProgLangs3 {
            get {
                return ResourceManager.GetString("ProgLangs3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ООП.
        /// </summary>
        public static string ProgrammingParadigms {
            get {
                return ResourceManager.GetString("ProgrammingParadigms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2008-2019 гг.: МБОУ гимназия №54, 1-11 класс.
        /// </summary>
        public static string School {
            get {
                return ResourceManager.GetString("School", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Делегирование задач.
        /// </summary>
        public static string SoftSkills1 {
            get {
                return ResourceManager.GetString("SoftSkills1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Умение слушать собеседника.
        /// </summary>
        public static string SoftSkills2 {
            get {
                return ResourceManager.GetString("SoftSkills2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Работа в команде.
        /// </summary>
        public static string SoftSkills3 {
            get {
                return ResourceManager.GetString("SoftSkills3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Критичность.
        /// </summary>
        public static string SoftSkills4 {
            get {
                return ResourceManager.GetString("SoftSkills4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Git.
        /// </summary>
        public static string VCS {
            get {
                return ResourceManager.GetString("VCS", resourceCulture);
            }
        }
    }
}
