//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterWebMiningApp.Localization.Abstract {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LAbstract {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LAbstract() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MasterWebMiningApp.Localization.Abstract.LAbstract", typeof(LAbstract).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Содержание.
        /// </summary>
        public static string Contents {
            get {
                return ResourceManager.GetString("Contents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Планируемые практические результаты.
        /// </summary>
        public static string ExpectedResults {
            get {
                return ResourceManager.GetString("ExpectedResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Планируемыми результатами работы являются:.
        /// </summary>
        public static string ExpectedResultsBody1 {
            get {
                return ResourceManager.GetString("ExpectedResultsBody1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Архитектура системы.
        /// </summary>
        public static string ExpectedResultsBody2 {
            get {
                return ResourceManager.GetString("ExpectedResultsBody2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПО для автоматизации бизнес-процессов в сфере исполнения заказов.
        /// </summary>
        public static string ExpectedResultsBody3 {
            get {
                return ResourceManager.GetString("ExpectedResultsBody3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цели и задачи.
        /// </summary>
        public static string Goals {
            get {
                return ResourceManager.GetString("Goals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Целью работы является разработка ПО для автоматизации бизнес-процессов в сфере исполнения заказов. Для достижения поставленной цели необходимо решить ряд задач, в число которых входят:.
        /// </summary>
        public static string GoalsBody1 {
            get {
                return ResourceManager.GetString("GoalsBody1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to разработать архитектуру системы.
        /// </summary>
        public static string GoalsBody2 {
            get {
                return ResourceManager.GetString("GoalsBody2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to разработать схему БД.
        /// </summary>
        public static string GoalsBody3 {
            get {
                return ResourceManager.GetString("GoalsBody3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to разработать функциональные блокои системы.
        /// </summary>
        public static string GoalsBody4 {
            get {
                return ResourceManager.GetString("GoalsBody4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to разработать матрицу доступа к функциональным блокам системы.
        /// </summary>
        public static string GoalsBody5 {
            get {
                return ResourceManager.GetString("GoalsBody5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Реферат на тему: Разработка программного средства в сфере исполнения заказов для назначения заказов курьерам.
        /// </summary>
        public static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рисунок 1 – схема Authorization Code Flow with PKCE.
        /// </summary>
        public static string ImgTitle1 {
            get {
                return ResourceManager.GetString("ImgTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рисунок 2 – Архитектура приложения.
        /// </summary>
        public static string ImgTitle2 {
            get {
                return ResourceManager.GetString("ImgTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рисунок 3 – Пример интерфейса приложения.
        /// </summary>
        public static string ImgTitle3 {
            get {
                return ResourceManager.GetString("ImgTitle3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введение.
        /// </summary>
        public static string Intro {
            get {
                return ResourceManager.GetString("Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На многих Интернет-площадках сферы различных услуг используется способ доставки «доставка курьером». К настоящему времени основные операции по реализации этой доставки практически отработаны и почти повсеместно встает запрос на автоматизацию этой деятельности. Конечный пользователь формирует заказ во внешней системе, после чего информация о заказе попадает в базу данных. За назначение заказа курьеру ответственным является оператор системы. Он проверяет данные по заказу и выбирает курьера, которому будет наз [rest of string was truncated]&quot;;.
        /// </summary>
        public static string IntroBody {
            get {
                return ResourceManager.GetString("IntroBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Библиографический список.
        /// </summary>
        public static string Literature {
            get {
                return ResourceManager.GetString("Literature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFC 7636 – Proof Key For Code Exchange by OAuth Public Clients – [Электронный ресурс] – (Eng) – URL:.
        /// </summary>
        public static string LiteratureBody1 {
            get {
                return ResourceManager.GetString("LiteratureBody1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization Code Flow with Proof Key for Code Exchange (PKCE) – [Электронный ресурс] – (Eng) – URL:.
        /// </summary>
        public static string LiteratureBody2 {
            get {
                return ResourceManager.GetString("LiteratureBody2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Основная часть.
        /// </summary>
        public static string MainPart {
            get {
                return ResourceManager.GetString("MainPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У заказа предусмотрено 5 состояний: «не назначен»; «назначен»; «выполняется»; «произошло ЧП»; «завершен». По структуре ПС содержит ряд функциональных блоков. Функциональный блок «авторизация/аутентификация» предназначен для авторизации и аутентификации пользователя в системе при помощи iDP (identity provider) Auth0. Для аутентификации и авторизации используется схема Authorization Code Flow with Proof Key for Code Exchange (PKCE) (рис.1)..
        /// </summary>
        public static string MainPartBody1 {
            get {
                return ResourceManager.GetString("MainPartBody1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Функциональный блок «выполняемый заказ» позволяет курьеру просмотреть подробности доставляемого заказа и время, прошедшее с момента начала работы, у оператора есть такая же возможность, но он может просмотреть любой заказ..
        /// </summary>
        public static string MainPartBody10 {
            get {
                return ResourceManager.GetString("MainPartBody10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Функциональный блок «список архивных заказов» позволяет оператору просмотреть архив заказов в статусе «выполнен» или «произошло ЧП» для определения основной информации о заказе..
        /// </summary>
        public static string MainPartBody11 {
            get {
                return ResourceManager.GetString("MainPartBody11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Функциональный блок «детализация информации о заказе» позволяет пользователям просмотреть подробную информацию о заказе. Дополнительно, операторам доступна возможность назначить заказ курьеру в случае, когда установлен статус «не назначен», а курьерам доступна возможность взять заказ в работу..
        /// </summary>
        public static string MainPartBody12 {
            get {
                return ResourceManager.GetString("MainPartBody12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Функциональный блок «детализация информации о курьере» позволяет оператору просмотреть подробную информацию о курьере, историю его заказов, а также отобразить статистику прибыли за определенный период..
        /// </summary>
        public static string MainPartBody13 {
            get {
                return ResourceManager.GetString("MainPartBody13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Архитектура приложения, изображенная на рис. 2, состоит из 4 элементов: клиентское приложение, idP, Web api и сервер БД..
        /// </summary>
        public static string MainPartBody14 {
            get {
                return ResourceManager.GetString("MainPartBody14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПС реализовано как одностраничное веб-приложение. Логика ПС написана на C# с использованием фреймворка Blazor, разметка – HTML, CSS, Razor Pages, web api – C# с использованием фреймворка ASP.NET Core, СУБД – PostgreSQL 13. На рис.3 изображен пример интерфейса ПС..
        /// </summary>
        public static string MainPartBody15 {
            get {
                return ResourceManager.GetString("MainPartBody15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - A. Клиентское приложение создает и сохраняет у себя криптографический ключ (code_verifier), а также создает на его основе новый криптографический ключ (t(code_verifier)) также называемый code_challenge. Приложение отправляет запрос к конечной точке авторизации на сервере Auth0, содержащий code_challenge и метод трансформации t_m;.
        /// </summary>
        public static string MainPartBody2 {
            get {
                return ResourceManager.GetString("MainPartBody2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - B. Сервер сохраняет себе пару code_challenge и t_m и в ответ клиенту добавляет код авторизации, который будет использоваться в дальнейшем при доступе к ресурсам приложения;.
        /// </summary>
        public static string MainPartBody3 {
            get {
                return ResourceManager.GetString("MainPartBody3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - C. Клиентское приложение отправляет запрос на получение токена доступа к соответствующей конечной точке на сервере Auth0, содержащее код авторизации и code_verifier;.
        /// </summary>
        public static string MainPartBody4 {
            get {
                return ResourceManager.GetString("MainPartBody4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - D. Сервер применяет сохраненный метод t_m на code_verifier из запроса и сравнивает его с code_challenge. Если значения совпадают, то сервер возвращает токен доступа и вариативные данные, например роль пользователя. Даже, если злоумышленник завладеет кодом авторизации на шаге B, он не сможет получить токен доступа без code_verifier..
        /// </summary>
        public static string MainPartBody5 {
            get {
                return ResourceManager.GetString("MainPartBody5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Функциональный блок «ролевая модель» предназначен для обеспечения авторизованного доступа к ресурсам системы на основании ролевой модели. В табл.1 приведена матрица доступа к подсистемам в зависимости от роли..
        /// </summary>
        public static string MainPartBody6 {
            get {
                return ResourceManager.GetString("MainPartBody6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Функциональный блок «список неназначенных заказов» предоставляет оператору возможность просмотра не назначенных заказов и назначения заказа курьеру..
        /// </summary>
        public static string MainPartBody7 {
            get {
                return ResourceManager.GetString("MainPartBody7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Функциональный блок «список назначенных заказов» предоставляет курьеру возможность просмотра назначенных ему заказов и выбора одного из них..
        /// </summary>
        public static string MainPartBody8 {
            get {
                return ResourceManager.GetString("MainPartBody8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Функциональный блок «список курьеров» предоставляет оператору возможность просмотреть список курьеров, числящихся в организации, а также воспользоваться функциональным блоком «детализация информации о курьере»..
        /// </summary>
        public static string MainPartBody9 {
            get {
                return ResourceManager.GetString("MainPartBody9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заключение.
        /// </summary>
        public static string Outro {
            get {
                return ResourceManager.GetString("Outro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разработанное программное средство для назначения заказов курьерам обеспечивает безопасную аутентификацию и хранение личных данных пользователей, точность и оперативность работы всех элементов курьерской службы в сфере исполнения заказов..
        /// </summary>
        public static string OutroBody {
            get {
                return ResourceManager.GetString("OutroBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оператор.
        /// </summary>
        public static string TableCol1 {
            get {
                return ResourceManager.GetString("TableCol1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Курьер.
        /// </summary>
        public static string TableCol2 {
            get {
                return ResourceManager.GetString("TableCol2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Таблица 1 – Матрица доступа по ролям.
        /// </summary>
        public static string TableName {
            get {
                return ResourceManager.GetString("TableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список не назначенных заказов.
        /// </summary>
        public static string TableRow1 {
            get {
                return ResourceManager.GetString("TableRow1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список назначенных заказов.
        /// </summary>
        public static string TableRow2 {
            get {
                return ResourceManager.GetString("TableRow2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список курьеров.
        /// </summary>
        public static string TableRow3 {
            get {
                return ResourceManager.GetString("TableRow3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выполняемый заказ.
        /// </summary>
        public static string TableRow4 {
            get {
                return ResourceManager.GetString("TableRow4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список архивных заказов.
        /// </summary>
        public static string TableRow5 {
            get {
                return ResourceManager.GetString("TableRow5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Детализация информации о заказе.
        /// </summary>
        public static string TableRow6 {
            get {
                return ResourceManager.GetString("TableRow6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Детализация информации о курьере.
        /// </summary>
        public static string TableRow7 {
            get {
                return ResourceManager.GetString("TableRow7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автореферат Козиева АБ Разработка программного средства в сфере исполнения заказов для назначения заказов курьерам.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
